### ISSUE TITLE
Better repo name? 🤔

### ISSUE THREAD

**Issue by neruthes** [guanbinrui/node-stego#1]
Ref: https://github.com/DimensionDev/Meta/blob/master/articles/1--github-repo-naming.md

**Comment by guanbinrui** [comment]
What about **Stego-JS**?

> Steganography base on frequency domain implemented in JavaScript.

**Comment by neruthes** [comment]
> What about **Stego-JS**?
> 
> > Steganography base on frequency domain implemented in JavaScript.

Supposing that it is environment-independent, `Stego-JS` would be great. Otherwise, consider `Stego-NodeJS` and `Stego-Web`.

**Comment by guanbinrui** [comment]
> > What about **Stego-JS**?
> > > Steganography base on frequency domain implemented in JavaScript.
> 
> Supposing that it is environment-independent, `Stego-JS` would be great. Otherwise, consider `Stego-NodeJS` and `Stego-Web`.

Only a trivial difference between them so they are both included.

**Comment by neruthes** [comment]
> > > What about **Stego-JS**?
> > > > Steganography base on frequency domain implemented in JavaScript.
> > 
> > 
> > Supposing that it is environment-independent, `Stego-JS` would be great. Otherwise, consider `Stego-NodeJS` and `Stego-Web`.
> 
> Only a trivial difference between them so they are both included.

Great! Let the new name be `Stego-JS`. 😆

**Comment by guanbinrui** [comment]
I do not granted change any settings about this repo. Who can do me a favor? @neruthes @yisiliu 

+ Change the repo name from `node-stego` to `Stego-JS`
+ Change the repo desc to `Steganography base on frequency domain implemented in JavaScript.`

**Comment by neruthes** [comment]
I will.

**Comment by neruthes** [comment]
Done.
