### ISSUE TITLE
Bit Overflow detection - process.stderr.write() shouldn't be used in browser

### ISSUE THREAD

**Issue by nervetrip** [guanbinrui/node-stego#47]
The following code throws an uncaught error in browser environments:

```
if (encodeLen > sizeOfBlocks) {
    process.stderr.write('bits overflow! try to shrink text or reduce copies.\n')
}
```

Here is the error:
```
stego.ts:49 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'write')
    at encodeImg (stego.ts:49:20)
```

The code is located in two places:
- https://github.com/DimensionDev/Stego-JS/blob/master/src/v2/stego.ts#L49
- https://github.com/DimensionDev/Stego-JS/blob/master/src/v1/stego.ts#L29

Can this code be refactored to throw an informative exception? This would allow web clients to detect and report more useful messaging to user when they attempt to encode more data than an image can hold.

**Comment by Jack-Works** [comment]
thanks, 0.15.0 contains the fix of this issue
